"""Session semantics shared by the backtest engine, the paper runner and strategies (#396).

Owns: session identity (exchange calendar, early closes), bar visibility (completed bars;
regular hours for ``same_session`` runs), the session-end flatten deadline, held-days
counting and history-warmup sizing. Pure: stdlib + pandas + numpy, no I/O, and it never
reads a clock -- callers pass ``now`` (aware) in.
"""

from __future__ import annotations

import functools
import math
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from datetime import UTC, date, datetime, time, timedelta
from typing import Any
from zoneinfo import ZoneInfo

import numpy as np
import pandas as pd

from milodex.data.timeframes import bar_size_minutes_from_timeframe, timeframe_from_bar_size

_ET_NAME = "America/New_York"
ET = ZoneInfo(_ET_NAME)
_REGULAR_CLOSE = time(16, 0)


@dataclass(frozen=True)
class Session:
    """One trading day. ``open``/``close`` are aware UTC; an early close shows in ``close``."""

    day: date
    open: datetime
    close: datetime


class CalendarCoverageError(LookupError):
    """A query fell outside the calendar's coverage window."""


@functools.cache
def _hhmm(value: str) -> time:
    return datetime.strptime(value, "%H:%M").time()


def _utc(day: date, wall: time) -> datetime:
    return datetime.combine(day, wall, tzinfo=ET).astimezone(UTC)


def session_day(ts: datetime | pd.Timestamp) -> date:
    """ET calendar date of an aware bar timestamp: the session day the bar belongs to."""
    if ts.tzinfo is None:
        raise ValueError("timestamp must be timezone-aware")
    return ts.astimezone(ET).date()


class SessionCalendar:
    """Exchange sessions over a coverage window; a day inside it with no session is closed."""

    def __init__(self, coverage: tuple[date, date], sessions: Mapping[date, Session]) -> None:
        self._coverage = coverage
        self._sessions = dict(sessions)

    @classmethod
    def from_rows(cls, payload: Mapping[str, Any]) -> SessionCalendar:
        """Build from a ``research_calendar()`` / ``calendar.json`` payload.

        Coverage is ``[window_start, window_end]``; ``sessions`` lists the open days only.
        Raises ``ValueError`` on any malformed payload.
        """
        try:
            if payload["timezone"] != _ET_NAME:
                raise ValueError(f"calendar timezone must be {_ET_NAME}: {payload['timezone']!r}")
            start = date.fromisoformat(payload["window_start"])
            end = date.fromisoformat(payload["window_end"])
            rows = [
                (date.fromisoformat(r["date"]), _hhmm(r["open"]), _hhmm(r["close"]))
                for r in payload["sessions"]
            ]
        except (KeyError, TypeError) as exc:
            raise ValueError(f"malformed calendar payload: {exc!r}") from exc
        days = [day for day, _, _ in rows]
        if start > end or days != sorted(set(days)):
            raise ValueError("calendar window is reversed or sessions are unordered/duplicated")
        if days and (days[0] < start or days[-1] > end):
            raise ValueError("calendar session outside its window")
        sessions: dict[date, Session] = {}
        for day, open_t, close_t in rows:
            if open_t >= close_t:
                raise ValueError(f"calendar session {day} closes at or before it opens")
            sessions[day] = Session(day, _utc(day, open_t), _utc(day, close_t))
        return cls((start, end), sessions)

    @classmethod
    @functools.cache
    def xnys(cls) -> SessionCalendar:
        """The committed NYSE table, generated by ``scripts/generate_xnys_calendar.py``."""
        # Imported here so the generator still runs when the committed table is missing/broken.
        from milodex.data import _xnys_calendar

        return cls.from_rows(_expand_table(_xnys_calendar))

    @property
    def coverage(self) -> tuple[date, date]:
        return self._coverage

    def session(self, day: date) -> Session | None:
        """The session on ``day``; ``None`` when closed. Raises outside coverage."""
        start, end = self._coverage
        if not start <= day <= end:
            raise CalendarCoverageError(f"{day} is outside calendar coverage {start}..{end}")
        return self._sessions.get(day)

    def is_early_close(self, day: date) -> bool:
        """True when ``day`` closes before 16:00 ET; False on a closed day."""
        session = self.session(day)
        return session is not None and session.close.astimezone(ET).time() < _REGULAR_CLOSE


def _expand_table(table: Any) -> dict[str, Any]:
    """Expand the compact generated table into the ``calendar.json`` payload shape.

    ``table`` is anything exposing the ``_xnys_calendar`` constants (the module itself, or
    the generator's in-memory equivalent).
    """
    start = date.fromisoformat(table.COVERAGE_START)
    end = date.fromisoformat(table.COVERAGE_END)
    closed = set(table.CLOSED_WEEKDAYS)
    special = dict(table.SPECIAL_SESSIONS)
    sessions = []
    for offset in range((end - start).days + 1):
        day = start + timedelta(days=offset)
        iso = day.isoformat()
        if day.weekday() >= 5 or iso in closed:
            continue
        open_, close = special.pop(iso, (table.REGULAR_OPEN, table.REGULAR_CLOSE))
        sessions.append({"date": iso, "open": open_, "close": close})
    if special:
        raise ValueError(f"special sessions on non-session days: {sorted(special)}")
    return {
        "source": table.SOURCE,
        "fetched_at": table.FETCHED_AT,
        "timezone": _ET_NAME,
        "window_start": table.COVERAGE_START,
        "window_end": table.COVERAGE_END,
        "sessions": sessions,
    }


def regular_hours_mask(ts_utc: pd.DatetimeIndex) -> np.ndarray:
    """Return a vectorized mask for US-equity regular-session bar starts."""
    eastern = ts_utc.tz_convert(_ET_NAME)
    minute_of_day = eastern.hour * 60 + eastern.minute
    return np.asarray((minute_of_day >= 9 * 60 + 30) & (minute_of_day < 16 * 60))


def held_days(bar_days: Iterable[date], opened_on: date, as_of: date) -> int:
    """Trading days after ``opened_on`` up to and including ``as_of``.

    ``|{d in bar_days : opened_on < d <= as_of}|`` -- the backtest kernel's own definition
    (it ticks once per outer bar day), in closed form. ``bar_days`` is the engine's
    ``trading_days``: the UTC dates of bar stamps across all symbols
    (``_trading_days_in_range`` in ``backtesting/engine.py``), not exchange sessions.
    Duplicate days count once.
    """
    return sum(1 for day in set(bar_days) if opened_on < day <= as_of)


def warmup_calendar_days(declared: int, parameters: Mapping[str, Any]) -> int:
    """Return the number of calendar days to prepend before the run window.

    ``declared`` is ``strategy.max_lookback_periods()``; ``parameters`` is the strategy
    config's parameter mapping. Resolution order:

    1. ``declared`` -- if non-zero, convert it to calendar days using a 1.4x
       trading-to-calendar multiplier (5 trading days / 7 calendar, rounded up generously)
       plus a 30-day buffer for holiday variation. This covers strategies whose lookback is
       expressed as a float param or nested in a sub-dict -- cases that the integer-param
       heuristic (step 2) cannot reach.
    2. Integer-param heuristic -- scan ``parameters`` values, take the largest *numeric
       whole-number* value (int or float-that-is-whole), multiply by 3 to convert trading
       periods to calendar days, floor at 365.  ``bool`` values are excluded (they are
       ``int`` subclasses but not lookback periods).
    """
    # Step 1: strategy-declared maximum lookback.
    if declared > 0:
        # 1.4 calendar days per trading day (= 7/5), rounded up, plus 30-day buffer.
        return math.ceil(declared * 1.4) + 30

    # Step 2: heuristic — scan parameter values for the largest numeric
    # whole-number (covers both int and float like 200.0).  Exclude booleans
    # (bool is a subclass of int in Python) and negative/zero values.
    # Whole-number constraint keeps fractional multipliers (e.g. 2.0 meaning
    # "2× ATR") from being mis-interpreted as lookback periods; the 365-day
    # floor is the safety net for strategies with small integer params.
    numeric_params = [
        int(v)
        for v in parameters.values()
        if isinstance(v, (int, float)) and not isinstance(v, bool) and v > 0 and float(v) == int(v)
    ]
    largest = max(numeric_params, default=30)
    # ponytail: cap at 10 years — no real strategy needs more lookback, and an
    # un-capped heuristic lets a large non-lookback param (e.g. a seed) explode
    # `start - timedelta(days=...)` into an OverflowError.
    return min(3650, max(365, largest * 3))


@dataclass(frozen=True)
class SessionPolicy:
    """Session rules for one strategy run (build with :meth:`for_tempo`).

    ``bar`` is the bar window (``timedelta(days=1)`` for 1D). ``calendar`` is set exactly
    when ``same_session``: multi-session and daily runs (crypto included) never touch XNYS.
    """

    same_session: bool
    bar: timedelta
    calendar: SessionCalendar | None = None
    flatten_lead: timedelta = timedelta(minutes=5)

    def __post_init__(self) -> None:
        if self.same_session and self.calendar is None:
            raise ValueError("a same_session policy requires a calendar")

    @classmethod
    def for_tempo(
        cls, tempo: Mapping[str, Any], calendar: SessionCalendar | None = None
    ) -> SessionPolicy:
        """Policy for a strategy ``tempo`` block.

        ``same_session`` only for an intraday bar declaring ``position_lifecycle:
        same_session``; only then is a calendar attached (``xnys()`` unless one is given).
        """
        bar_size = tempo["bar_size"]
        if bar_size == "1D":
            return cls(same_session=False, bar=timedelta(days=1))
        minutes = bar_size_minutes_from_timeframe(timeframe_from_bar_size(bar_size))
        bar = timedelta(minutes=minutes)
        if tempo.get("position_lifecycle", "multi_session") != "same_session":
            return cls(same_session=False, bar=bar)
        if calendar is None:
            calendar = SessionCalendar.xnys()
        return cls(same_session=True, bar=bar, calendar=calendar)

    def visible(self, bar_starts: pd.DatetimeIndex, now: datetime | None = None) -> np.ndarray:
        """Mask of bars a run may see: completed by ``now``, and regular-hours if same_session.

        Completion is intraday-only: a daily bar's completion belongs to the runner's lock-in
        gate, so ``now`` on a 1D policy raises. Naive ``bar_starts`` or ``now`` raise.
        """
        if bar_starts.tz is None:
            raise ValueError("bar_starts must be timezone-aware")
        mask = np.ones(len(bar_starts), dtype=bool)
        if now is not None:
            if now.tzinfo is None:
                raise ValueError("now must be timezone-aware")
            if self.bar >= timedelta(days=1):
                raise ValueError(
                    "visible(now=...) is intraday-only; the runner's lock-in gate owns 1D"
                )
            mask &= np.asarray(bar_starts + self.bar <= now)
        if self.same_session:
            mask &= regular_hours_mask(bar_starts)
        return mask

    def flatten_deadline(self, day: date, broker_next_close: datetime | None) -> datetime | None:
        """UTC instant to flatten ``day``'s same_session positions; ``None`` if not applicable.

        The earlier of the table close and the broker's next close wins (unscheduled early
        closes), minus ``flatten_lead``. ``None`` unless same_session, and on a closed day.
        """
        if not self.same_session:
            return None
        session = self.calendar.session(day)
        if session is None:
            return None
        close = session.close
        if broker_next_close is not None:
            close = min(close, broker_next_close)
        return close.astimezone(UTC) - self.flatten_lead

    def evaluation_open(self, now: datetime, broker_next_close: datetime | None) -> bool:
        """Whether a cycle may fetch and evaluate at ``now``; always True unless same_session.

        False on a closed day, outside ``[open, flatten_deadline)``, and once the broker's next
        close falls on a later ET day (no close left today: an unscheduled closure, or an
        unscheduled early close that has already passed).
        """
        if not self.same_session:
            return True
        today = session_day(now)
        deadline = self.flatten_deadline(today, broker_next_close)
        if deadline is None or (
            broker_next_close is not None and session_day(broker_next_close) > today
        ):
            return False
        return self.calendar.session(today).open <= now < deadline

    def overdue(self, opened_at: datetime, now: datetime) -> bool:
        """A same_session lot opened in an earlier ET session than ``now``'s.

        ``opened_at`` is the aware lot-open timestamp (the ledger's UTC ``recorded_at``); both
        sides are compared as ET dates here, so no caller can pass a UTC ``.date()``.
        """
        return self.same_session and session_day(opened_at) < session_day(now)
